version: '3'
services:
  frontend:
    build: ./client
    ports:
      - '5173:5173'
  backend:
    build: ./server
    ports:
      - '8000:8000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
